#include "../Common.hlsl"
#include "Packages/com.arycama.customrenderpipeline/ShaderLibrary/Random.hlsl"

#pragma kernel Compute
#pragma kernel Accumulate
#pragma use_dxc
#pragma require waveMath
#pragma multi_compile _ SHADOWS_ON
#pragma multi_compile _ POINT_LIGHTS_ON

RWTexture3D<float4> Result;
Texture3D<float4> Input;

float4x4 PixelToViewDir;
float IsFirst;

float SliceToLinearDepth(float slice)
{
	return slice / VolumeSize.z * MaxDepth;
}

[numthreads(8, 8, 1)]
void Compute(uint3 id : SV_DispatchThreadID)
{
	float jitter = Noise1D(id.xy);
	float3 pixelPosition = id + float2(0.5, jitter).xxy;
	float3 viewDir = MultiplyVector(PixelToViewDir, float3(pixelPosition.xy, 1.0));
	float eyeDepth = SliceToLinearDepth(pixelPosition.z);
	float3 viewPosition = viewDir * eyeDepth;
	
	float2 screenPosition = pixelPosition.xy / VolumeSize.xy;
	pixelPosition.xy = screenPosition * ViewSize;
	
	float3 illuminance;
	GetLuminance(0.0, viewPosition, pixelPosition.xy, illuminance);
	illuminance += AmbientLight;
	
	float viewDistance = length(viewPosition);
	float extinction = viewDistance > FogStart && viewDistance < FogEnd ? rcp(FogEnd - viewDistance) : 0.0;
	float3 albedo = FogColor / (SunColor + AmbientLight);
	float4 luminanceExtinction = float4(albedo * illuminance, extinction);
	
	// Reproject previous frame. Needs to use unjittered world position
	float linearUnjitteredDepth = SliceToLinearDepth(id.z + 0.5);
	float3 worldPosition = MultiplyPointProj(ScreenToWorld, float3(screenPosition, LinearToDeviceDepth(linearUnjitteredDepth))).xyz;
	float4 previousScreenPosition = MultiplyPoint(WorldToPreviousScreen, worldPosition);
	previousScreenPosition.xy = PerspectiveDivide(previousScreenPosition).xy;
	
	float3 volumeUv = float3(previousScreenPosition.xy, previousScreenPosition.w / MaxDepth);
	if (!IsFirst && all(saturate(volumeUv) == volumeUv))
	{
		float4 previousLuminanceExtinction = Input.SampleLevel(TrilinearClampSampler, volumeUv, 0.0);
		luminanceExtinction = lerp(previousLuminanceExtinction, luminanceExtinction, 0.05);
	}
	
	Result[id] = luminanceExtinction;
}

[numthreads(8, 8, 1)]
void Accumulate(uint2 id : SV_DispatchThreadID)
{
	float3 viewDirection = MultiplyVector(PixelToViewDir, float3(id + 0.5, 1.0));
	float ds = length(viewDirection) / VolumeSize.z * MaxDepth;
	
	float initialTransmittance = FogEnd == 0.0 ? 1.0 : saturate(FogEnd * rcp(FogEnd - FogStart));
	float3 initialLuminance = FogColor * saturate(1.0 - initialTransmittance);
	float4 result = float4(initialLuminance, initialTransmittance);
	for (uint i = 0; i < VolumeSize.z; i++)
	{
		float4 luminanceExtinction = Input[uint3(id, i)];
		float transmittance = exp(-luminanceExtinction.a * ds);
		result.rgb += result.a * luminanceExtinction.rgb * (1.0 - transmittance);
		result.a *= transmittance;
		Result[uint3(id, i)] = result;
	}
}
