#include "../Common.hlsl"
#include "Packages/com.arycama.customrenderpipeline/ShaderLibrary/Random.hlsl"

#pragma kernel Compute
#pragma kernel Accumulate
#pragma use_dxc
#pragma require waveMath

RWTexture3D<float4> Result;
Texture3D<float4> Input;

float4x4 PixelToWorldViewDir;

[numthreads(8, 8, 1)]
void Compute(uint3 id : SV_DispatchThreadID)
{
	float jitter = Hash12(id.xy + 0.5);//0.5; //Noise1D(id.xy);
	float3 worldDir = MultiplyVector(PixelToWorldViewDir, float3(id.xy + 0.5, 1.0));
	float rcpWorldDirLength = RcpLength(worldDir);
	worldDir *= rcpWorldDirLength;
	
	float eyeDepth = (id.z + jitter) / VolumeSize.z * MaxDepth;
	
	float viewDistance = eyeDepth * rcp(rcpWorldDirLength);
	float3 worldPosition = ViewPosition + worldDir * viewDistance;
	
	float2 screenPosition = (id.xy + 0.5) / VolumeSize.xy;
	float2 pixelPosition = screenPosition * ViewSize;
	
	float3 lighting = SunColor;
	float fade = saturate(eyeDepth * SunShadowFadeScale + SunShadowFadeOffset);
	float3 shadowPosition = MultiplyPoint3x4((float3x4) WorldToSunShadow, worldPosition);
	
	// Shadow
	if (fade && all(saturate(shadowPosition.xy) == shadowPosition.xy))
		lighting *= lerp(1.0, SunShadow.SampleCmpLevelZero(LinearClampCompareSampler, shadowPosition.xy, shadowPosition.z), fade);
	
	lighting += AmbientLight;
	
	screenPosition.y = 1 - screenPosition.y;
	
	// Flat bit array iterator scalarized on entity with Z-Bin masked words
	float3 cluster = GetClusterIndex(float3(screenPosition.xy * ViewSize, eyeDepth));
	uint2 lightRange = BitUnpack(LightDepthMinMax[cluster.z], 16, uint2(0, 16));
	uint2 mergedRange = uint2(WaveActiveMin(lightRange.x), WaveActiveMax(lightRange.y)) >> 5u;
	half3 luminance = 0.0h;
	
	// Read range of words of visibility bits
	for (uint i = mergedRange.x; i <= mergedRange.y; i++)
	{
		// Load bit mask data per lane
		uint tileMask = VisibleLightBits[uint3(cluster.xy, i)];
		
		// Mask by zbin mask
		uint localMin = clamp((int) lightRange.x - (int) (32 * i), 0, 31);
		uint maskWidth = clamp((int) lightRange.y - (int) lightRange.x + 1, 0, 32);
		
		// BitFieldMask op needs manual 32 size wrap support
		uint depthMask = maskWidth == 32u ? UintMax : ((1u << maskWidth) - 1u) << localMin;
		
		// Compact world bitmask over all lanes in wavefront
		uint mask = WaveActiveBitOr(tileMask & depthMask);
		
		while (mask != 0u)
		{
			uint bitIndex = firstbitlow(mask);
			uint lightIndex = 32u * i + bitIndex;
			mask &= ~(1u << bitIndex);
			
			Light light = PointLights[lightIndex];
	
			// Attenuation
			float3 lightVector = light.position - worldPosition;
			float distanceSquared = dot(lightVector, lightVector);
			float attenuation = saturate(1.0h - distanceSquared * light.rcpRangeSquared);
		
			float3 L = lightVector * rsqrt(distanceSquared);
			attenuation *= saturate(dot(light.forward, L) * light.angleScale + light.angleOffset);
			attenuation = Sq(attenuation);
			
			lighting += attenuation * light.color;
		}
	}
	
	float extinction = eyeDepth > FogStart && eyeDepth < FogEnd ? rcp(FogEnd - eyeDepth) : 0.0;
	float3 albedo = FogColor / (SunColor + AmbientLight);
	
	Result[id] = float4(albedo * lighting, extinction);
}

[numthreads(8, 4, 1)]
void Accumulate(uint2 id : SV_DispatchThreadID)
{
	float3 worldDirection = MultiplyVector(PixelToWorldViewDir, float3(id + 0.5, 1.0));
	float rayLength = MaxDepth * length(worldDirection);
	float ds = rayLength / VolumeSize.z;
	
	float4 result = float2(0.0, 1.0).xxxy;
	for (float i = 0.0; i < VolumeSize.z; i++)
	{
		// Attenuate due to atmosphere and local extinction
		float4 luminanceExtinction = Input[uint3(id, i)];
		float transmittance = exp(-luminanceExtinction.a * ds);
		
		result.rgb += result.a * luminanceExtinction.rgb * (1.0 - transmittance);
		result.a *= transmittance;
		Result[uint3(id, i)] = result;
	}
}
