/// <summary>
/// Stores record types names as an int, made from concatening four characters of that record type
/// </summary>
public enum RecordType
{
	Activator = 'A' + ('C' << 8) + ('T' << 16) + ('I' << 24),
	Alchemy = 'A' + ('L' << 8) + ('C' << 16) + ('H' << 24),
	Apparatus = 'A' + ('P' << 8) + ('P' << 16) + ('A' << 24),
	Armor = 'A' + ('R' << 8) + ('M' << 16) + ('O' << 24),
	BirthSign = 'B' + ('S' << 8) + ('G' << 16) + ('N' << 24),
	Book = 'B' + ('O' << 8) + ('O' << 16) + ('K' << 24),
	BodyPart = 'B' + ('O' << 8) + ('D' << 16) + ('Y' << 24),
	Cell = 'C' + ('E' << 8) + ('L' << 16) + ('L' << 24),
	Class = 'C' + ('L' << 8) + ('A' << 16) + ('S' << 24),
	Clothing = 'C' + ('L' << 8) + ('O' << 16) + ('T' << 24),
	Container = 'C' + ('O' << 8) + ('N' << 16) + ('T' << 24),
	Creature = 'C' + ('R' << 8) + ('E' << 16) + ('A' << 24),
	Dialogue = 'D' + ('I' << 8) + ('A' << 16) + ('L' << 24),
	Door = 'D' + ('O' << 8) + ('O' << 16) + ('R' << 24),
	Enchantment = 'E' + ('N' << 8) + ('C' << 16) + ('H' << 24),
	Faction = 'F' + ('A' << 8) + ('C' << 16) + ('T' << 24),
	GameSetting = 'G' + ('M' << 8) + ('S' << 16) + ('T' << 24),
	Global = 'G' + ('L' << 8) + ('O' << 16) + ('B' << 24),
	Ingredient = 'I' + ('N' << 8) + ('G' << 16) + ('R' << 24),
	Land = 'L' + ('A' << 8) + ('N' << 16) + ('D' << 24),
	LandTexture = 'L' + ('T' << 8) + ('E' << 16) + ('X' << 24),
	LevelledCreature = 'L' + ('E' << 8) + ('V' << 16) + ('C' << 24),
	LevelledItem = 'L' + ('E' << 8) + ('V' << 16) + ('I' << 24),
	Light = 'L' + ('I' << 8) + ('G' << 16) + ('H' << 24),
	Lockpick = 'L' + ('O' << 8) + ('C' << 16) + ('K' << 24),
	Info = 'I' + ('N' << 8) + ('F' << 16) + ('O' << 24),
	MagicEffect = 'M' + ('G' << 8) + ('E' << 16) + ('F' << 24),
	MiscItem = 'M' + ('I' << 8) + ('S' << 16) + ('C' << 24),
	Npc = 'N' + ('P' << 8) + ('C' << 16) + ('_' << 24),
	PathGrid = 'P' + ('G' << 8) + ('R' << 16) + ('D' << 24),
	Probe = 'P' + ('R' << 8) + ('O' << 16) + ('B' << 24),
	Race = 'R' + ('A' << 8) + ('C' << 16) + ('E' << 24),
	Region = 'R' + ('E' << 8) + ('G' << 16) + ('N' << 24),
	Repair = 'R' + ('E' << 8) + ('P' << 16) + ('A' << 24),
	Script = 'S' + ('C' << 8) + ('P' << 16) + ('T' << 24),
	Skill = 'S' + ('K' << 8) + ('I' << 16) + ('L' << 24),
	Sound = 'S' + ('O' << 8) + ('U' << 16) + ('N' << 24),
	SoundGenerator = 'S' + ('N' << 8) + ('D' << 16) + ('G' << 24),
	Spell = 'S' + ('P' << 8) + ('E' << 16) + ('L' << 24),
	Static = 'S' + ('T' << 8) + ('A' << 16) + ('T' << 24),
	Tes3 = 'T' + ('E' << 8) + ('S' << 16) + ('3' << 24),
	Weapon = 'W' + ('E' << 8) + ('A' << 16) + ('P' << 24),
}